spring:
  application:
    name: video-meet-backend
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/video_meet
    username: root
    # password: ${SPRING_DATASOURCE_PASSWORD}
    password: deep
    driver-class-name: com.mysql.cj.jdbc.Driver
